persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log


# MQTT TCP
listener 1883
protocol mqtt

# MQTT WebSocket
listener 9001
protocol websockets

allow_anonymous false
password_file /mosquitto/config/pwfile